server:
  port: ${PORT:8761} # Default port for Eureka server

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false  # This server does not register with itself
    fetch-registry: false        # This server does not fetch the registry
  instance:
    hostname: ${HOSTNAME:localhost}
  server:
    enable-self-preservation: false # Optional for testing environments
